Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Sneuss.Models
{
  public class SneussContextFactory : IDesignTimeDbContextFactory<SneussContext>
  {

    SneussContext IDesignTimeDbContextFactory<SneussContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<SneussContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new SneussContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Sneuss.Models
{
  public class Engineer
  {
    public Engineer ()
    {
      this.Machines = new HashSet<EngineerMachine>();
    }
    public int EngineerId {get;set;}
    public string Name {get;set;}
    public string Details {get;set;}
    public ICollection<EngineerMachine> Machines {get;}
  }
}

Factory/Models/EngineerMachine.cs
namespace Sneuss.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId {get; set;}
    public int EngineerId {get; set;}
    public int MachineId {get; set;}
    public Engineer Engineer {get; set;}
    public Machine Machine {get; set;}
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Sneuss.Models
{
  public class Machine
  {
    public Machine ()
    {
      this.Engineers = new HashSet<EngineerMachine>();
    }
    public int MachineId {get;set;}
    public string Name {get;set;}
    public string Details {get;set;}
    public string Status {get;set;} = "Operational";
    public ICollection<EngineerMachine> Engineers {get;}
  }
}

Factory/Models/SneussContext.cs
using Microsoft.EntityFrameworkCore;

namespace Sneuss.Models
{
  public class SneussContext : DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines {get; set; }
    public DbSet<EngineerMachine> EngineerMachine {get; set; }
    
    public SneussContext(DbContextOptions options) : base(options) { }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Sneuss.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Dynamic;
using System;

namespace Sneuss.Controllers
{
  public class EngineersController : Controller
  {
    private readonly SneussContext _db;

    public EngineersController(SneussContext db)
    {
      _db = db;
    }

    public ActionResult Index() 
    {
      var model = _db.Engineers
        .Include(eng => eng.Machines)
        .ThenInclude(join => join.Machine)
        .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer eng)
    {
      _db.Engineers.Add(eng);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
        .Include(eng => eng.Machines)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(eng => eng.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit (int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(eng => eng.EngineerId == id);
      ViewBag.Machines = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer eng)
    {
      _db.Entry(eng).State = EntityState.Modified; 
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(eng => eng.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    { 
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(eng => eng.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(eng => eng.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Machine mach, int EngineerId)
    {
      if (EngineerId != 0 && mach.MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() {EngineerId = EngineerId, MachineId = mach.MachineId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Sneuss.Models;
using System.Linq;

namespace Sneuss.Controllers
{
  public class HomeController : Controller
  {
    private readonly SneussContext _db;

    public HomeController(SneussContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      ViewBag.Engineers = _db.Engineers.ToList();
      ViewBag.Machines = _db.Machines.ToList();
      return View();
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Sneuss.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace Sneuss.Controllers
{
  public class MachinesController : Controller
  {
    private readonly SneussContext _db;

    public MachinesController(SneussContext db)
    {
      _db = db;
    }

    public ActionResult Index() 
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine mach)
    {
      _db.Machines.Add(mach);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(mach => mach.Engineers)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(mach => mach.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit (int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(mach => mach.MachineId == id);
      ViewBag.Engineers = new SelectList(_db.Machines, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine mach)
    {
      _db.Entry(mach).State = EntityState.Modified; 
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(mach => mach.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    { 
      Machine thisMachine = _db.Machines.FirstOrDefault(mach => mach.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(mach => mach.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Engineer eng, int MachineId)
    {
      if (MachineId != 0 && eng.EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() {MachineId = MachineId, EngineerId = eng.EngineerId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Sneuss.Models.Engineer

<h1 class="jumbotron">Add a Machine License</h1>

<h4>Add a Machine License to this Engineer: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Select Machine")
  @Html.DropDownList("MachineId")

  <input class="btn btn-success" type="submit" value="Add" />
}

<input type="button" class="btn btn-primary" value="Back to Engineer List" onclick="location.href='@Url.Action("Index", "Engineers")'" />

Factory/Views/Engineers/Create.cshtml
@{
  Layout ="_Layout";
}

@model Sneuss.Models.Engineer

<h2 class="jumbotron">Add a new Engineer</h4>


@using (Html.BeginForm())
{
  <div class="form-group">
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control"})
  </div>
  <div class="form-group">
    @Html.LabelFor(model => model.Details)
    @Html.TextBoxFor(model => model.Details, new { @class = "form-control"})<br>
  </div>
  <input type="submit" class="btn btn-primary" value="Add" />
}

<input type="button" class="btn btn-primary" value="Back to Engineer List" onclick="location.href='@Url.Action("Index", "Engineers")'" />

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Sneuss.Models.Engineer

<h2 class="jumbotron">Delete Engineer</h2>

<p>Are you sure you want to delete this Engineer?</p>


<p>Name: @Html.DisplayFor(model => model.Name)</p>
@using (Html.BeginForm())
{
  <input type="submit" class="btn btn-danger" value="Delete" />
}

<input type="button" class="btn btn-primary" value="Back to Engineer List" onclick="location.href='@Url.Action("Index", "Engineers")'" />

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}
@using Sneuss.Models;
@model Sneuss.Models.Engineer;

<h1 class="jumbotron">Engineer Details</h1>
<hr/>
<h4>Name: @Html.DisplayFor(model => model.Name)</h4>
<hr/>
<h4>Details: @Html.DisplayFor(model => model.Details)</h4>
<hr/>

@if(@Model.Machines.Count == 0)
{
  <p>This engineer doesn't have any licenses yet.</p>
}
else
{
  <h4>Machines licensed on:</h4>
  <ul>
  @foreach(var join in Model.Machines)
  {
    <li>@join.Machine.Name</li>
    @using (Html.BeginForm("DeleteMachine", "Engineers"))
    {
    @Html.Hidden("joinId", @join.EngineerMachineId)
    <input class="btn btn-danger" type="submit" value="Delete"/>
    }
  }
  </ul>
}

<input type="button" class="btn btn-primary" value="Add Machine License" onclick="location.href='@Url.Action("AddMachine", "Engineers", new { id = Model.EngineerId })'" /><br>
<input type="button" class="btn btn-primary" value="Back to Engineer List" onclick="location.href='@Url.Action("Index", "Engineers")'" />

Factory/Views/Engineers/Edit.cshtml
@{
Layout = "_Layout";
}

@model Sneuss.Models.Engineer

<h2 class="jumbotron">Edit @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)
  <div class="form-group">
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control"})
  </div>
  <div class="form-group">
    @Html.LabelFor(model => model.Details)
    @Html.TextBoxFor(model => model.Details, new { @class = "form-control"})<br>
  </div>
  <input type="submit" class="btn btn-primary" value="Save" />
}

<input type="button" class="btn btn-primary" value="Back to Engineer List" onclick="location.href='@Url.Action("Index", "Engineers")'" />

Factory/Views/Engineers/Index.cshtml
@{
  Layout ="_Layout";
}

@using Sneuss.Models;
@model List<Sneuss.Models.Engineer>;

<h1 class="jumbotron"> Engineers </h1>

  @if(@Model.Count == 0)
  {
    <h3> No Engineers have been added yet.</h3>
  }

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Details</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  @foreach(Engineer eng in Model) 
    {
      <tr>
      <td>@eng.Name </td>
      <td>@eng.Details</td>
      <td>@Html.ActionLink("Edit", "Edit", new { id = eng.EngineerId })  |  @Html.ActionLink("Details", "Details", new { id = eng.EngineerId}) | @Html.ActionLink("Delete", "Delete", new { id = eng.EngineerId})</td>
      </tr>
    }
  </tbody>
</table> 

<input type="button" class="btn btn-primary" value="Add a New Engineer" onclick="location.href='@Url.Action("Create", "Engineers")'" />
<input type="button" class="btn btn-primary" value="Home" onclick="location.href='@Url.Action("Index", "Home")'" />

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

@using Sneuss.Models;

<h1 class="jumbotron text-center">Welcome to the Factory</h1>

<h2>Engineers and Machines</h2>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Details</th>
      <th>Type</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  @foreach(Engineer eng in ViewBag.Engineers) 
    {
      <tr>
      <td>@eng.Name </td>
      <td>@eng.Details</td>
      <td>Engineer</td>
      <td>@Html.ActionLink("Edit", "Edit", "Engineers", new { id = eng.EngineerId })  |  @Html.ActionLink("Details", "Details", "Engineers", new { id = eng.EngineerId}) | @Html.ActionLink("Delete", "Delete", "Engineers", new { id = eng.EngineerId})</td>
      </tr>
    }
    @foreach(Machine mach in ViewBag.Machines) 
    {
      <tr>
      <td>@mach.Name </td>
      <td>@mach.Details</td>
      <td>Machine</td>
      <td>@Html.ActionLink("Edit", "Edit", "Machines", new { id = mach.MachineId })  |  @Html.ActionLink("Details", "Details", "Machines", new { id = mach.MachineId}) | @Html.ActionLink("Delete", "Delete", "Machines", new { id = mach.MachineId})</td>
      </tr>
    }
  </tbody>
</table>

<input type="button" class="btn btn-primary" value="View Engineers" onclick="location.href='@Url.Action("Index", "Engineers")'" />
<input type="button" class="btn btn-primary" value="View Machines" onclick="location.href='@Url.Action("Index", "Machines")'" />

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Sneuss.Models.Machine

<h1 class="jumbotron">Add an Engineer</h1>

<h4>Add a Engineer to this Machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId")

  <input class="btn btn-success" type="submit" value="Add" />
}

<input type="button" class="btn btn-primary" value="Back to Machine List" onclick="location.href='@Url.Action("Index", "Machines")'" />

Factory/Views/Machines/Create.cshtml
@{
  Layout ="_Layout";
}

@model Sneuss.Models.Machine

<h2 class="jumbotron">Add a new Engineer</h4>


@using (Html.BeginForm())
{
  <div class="form-group">
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control"})
  </div>
  <div class="form-group">
    @Html.LabelFor(model => model.Details)
    @Html.TextBoxFor(model => model.Details, new { @class = "form-control"})<br>
  </div>
  <input type="submit" class="btn btn-primary" value="Add" />
}

<input type="button" class="btn btn-primary" value="Back to Machine List" onclick="location.href='@Url.Action("Index", "Machines")'" />

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Sneuss.Models.Machine

<h2 class="jumbotron">Delete Machine</h2>

<p>Are you sure you want to delete this Machine?</p>


<p>Name: @Html.DisplayFor(model => model.Name)</p>
@using (Html.BeginForm())
{
  <input type="submit" class="btn btn-danger" value="Delete" />
}

<input type="button" class="btn btn-primary" value="Back to Engineer List" onclick="location.href='@Url.Action("Index", "Machines")'" />

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}
@using Sneuss.Models;
@model Sneuss.Models.Machine;

<h2 class="jumbotron">Machine Details</h2>
<hr/>
<h4>Name: @Html.DisplayFor(model => model.Name)</h4>
<hr/>
<h4>Details: @Html.DisplayFor(model => model.Details)</h4>
<hr/>
<h4>Status: @Html.DisplayFor(model => model.Status)</h4>
<hr/>

@if(@Model.Engineers.Count == 0)
{
  <p>This Machine doesn't have any engineers yet.</p>
}
else
{
  <h4>Engineers that can work on me:</h4>
  <ul>
  @foreach(var join in Model.Engineers)
  {
    <li>@join.Engineer.Name</li>
    @using (Html.BeginForm("DeleteEngineer", "Engineers"))
    {
    @Html.Hidden("joinId", @join.EngineerMachineId)
    <input class="btn btn-danger" type="submit" value="Delete"/>
    }
  }
  </ul>
}

<input type="button" class="btn btn-primary" value="Add Engineer" onclick="location.href='@Url.Action("AddEngineer", "Machines", new { id = Model.MachineId })'" /><br>
<input type="button" class="btn btn-primary" value="Back to Machine List" onclick="location.href='@Url.Action("Index", "Machines")'" />

Factory/Views/Machines/Edit.cshtml
@{
Layout = "_Layout";
}

@model Sneuss.Models.Machine

<h2 class="jumbotron">Edit @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  <div class="form-group">
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control"})
  </div>
  <div class="form-group">
    @Html.LabelFor(model => model.Details)
    @Html.TextBoxFor(model => model.Details, new { @class = "form-control"})<br>
  </div>
  <p>Status:</p>
  <div class="form-check">
    @Html.RadioButtonFor(model => model.Status, "Operational", new { @class="form-check-input" })
    @Html.Label("one", "Operational", new { @class = "form-check-label" })<br>
    @Html.RadioButtonFor(model => model.Status, "Malfunctioning", new { @class = "form-check-input" })
    @Html.Label("two", "Malfunctioning", new { @class = "form-check-label" })<br>
    @Html.RadioButtonFor(model => model.Status, "Being Repaired", new { @class = "form-check-input" })
    @Html.Label("three", "Being Repaired", new { @class = "form-check-label" })<br>
  </div>
  <input type="submit" class="btn btn-primary" value="Save" />
}

<input type="button" class="btn btn-primary" value="Back to Machine List" onclick="location.href='@Url.Action("Index", "Machines")'" />

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Sneuss.Models; 
@model List<Sneuss.Models.Machine>;

<h1 class="jumbotron">Machines</h1>

@if (@Model.Count == 0)
{
  <h3> No Machines Have Been Added yet </h3>
}

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Details</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  @foreach(Machine mach in Model) 
    {
      <tr>
      <td>@mach.Name </td>
      <td>@mach.Details</td>
      <td>@Html.ActionLink("Edit", "Edit", new { id = mach.MachineId })  |  @Html.ActionLink("Details", "Details", new { id = mach.MachineId}) | @Html.ActionLink("Delete", "Delete", new { id = mach.MachineId})</td>
      </tr>
    }
  </tbody>
</table> 

<input type="button" class="btn btn-primary" value="Add a New Machine" onclick="location.href='@Url.Action("Create", "Machines")'" />
<input type="button" class="btn btn-primary" value="Home" onclick="location.href='@Url.Action("Index", "Home")'" />

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sneuss Factory</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
    @RenderBody()
    </div>
  </body>
</html>